version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    environment:
    # if you want pretty colors in your docker logs:
    - FORCE_COLOR=1
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - ./data/mysql:/var/lib/mysql
#LETSENCRYPT CLOUDFLARE DNS CHALLANGE
  letsencrypt:
    image: adferrand/letsencrypt-dns
    container_name: "letsencrypt-dns"
    env_file: .env
    volumes:
      - "$ROOT/domains.conf:/etc/letsencrypt/domains.conf"
      - "$ROOT/certs/:/etc/letsencrypt"
    environment:
      - VERSION=latest
      - "LETSENCRYPT_USER_MAIL=$EMAIL"
      - "LEXICON_PROVIDER=$PROVIDER"
      - "LEXICON_PROVIDER_OPTIONS=$PROVIDER_OPTIONS"
      - "CERTS_DIRS_MODE=$DIRS_MODE"
      - "CERTS_FILES_MODE=$FILES_MODE"
    restart: always
