# WARNING: This is a CI docker-compose file used for building and testing of the entire app, it should not be used for production.
version: "3"
services:

  fullstack:
    image: ${IMAGE}:ci-${BUILD_NUMBER}
    environment:
      - LOG_LEVEL=debug
    volumes:
      - npm_data_ci:/data
      - ../docs:/temp-docs

  cypress:
    image: ${IMAGE}-cypress:ci-${BUILD_NUMBER}
    build:
      context: ../
      dockerfile: test/cypress/Dockerfile
    environment:
      CYPRESS_baseUrl: "http://fullstack:81"
    volumes:
      - cypress-logs:/results
    command: cypress run --browser chrome --config-file=${CYPRESS_CONFIG:-cypress/config/ci.json}

volumes:
  cypress-logs:
  npm_data_ci:
